# ruff.toml
[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "YTT", # flake8-2020
    "S",   # flake8-bandit
]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/*" = ["S101"] # Allow assert in tests

[lint.isort]
known-first-party = ["ai_algos"]
